// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculatorService/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calculating struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculating) Reset()         { *m = Calculating{} }
func (m *Calculating) String() string { return proto.CompactTextString(m) }
func (*Calculating) ProtoMessage()    {}
func (*Calculating) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{0}
}

func (m *Calculating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculating.Unmarshal(m, b)
}
func (m *Calculating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculating.Marshal(b, m, deterministic)
}
func (m *Calculating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculating.Merge(m, src)
}
func (m *Calculating) XXX_Size() int {
	return xxx_messageInfo_Calculating.Size(m)
}
func (m *Calculating) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculating.DiscardUnknown(m)
}

var xxx_messageInfo_Calculating proto.InternalMessageInfo

func (m *Calculating) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Calculating) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type CalculatorRequest struct {
	Calculating          *Calculating `protobuf:"bytes,1,opt,name=calculating,proto3" json:"calculating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CalculatorRequest) Reset()         { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()    {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{1}
}

func (m *CalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorRequest.Unmarshal(m, b)
}
func (m *CalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorRequest.Merge(m, src)
}
func (m *CalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorRequest.Size(m)
}
func (m *CalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorRequest proto.InternalMessageInfo

func (m *CalculatorRequest) GetCalculating() *Calculating {
	if m != nil {
		return m.Calculating
	}
	return nil
}

type CalculatorResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorResponse) Reset()         { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()    {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{2}
}

func (m *CalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorResponse.Unmarshal(m, b)
}
func (m *CalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorResponse.Merge(m, src)
}
func (m *CalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorResponse.Size(m)
}
func (m *CalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorResponse proto.InternalMessageInfo

func (m *CalculatorResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type CalculatingManyTimes struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatingManyTimes) Reset()         { *m = CalculatingManyTimes{} }
func (m *CalculatingManyTimes) String() string { return proto.CompactTextString(m) }
func (*CalculatingManyTimes) ProtoMessage()    {}
func (*CalculatingManyTimes) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{3}
}

func (m *CalculatingManyTimes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatingManyTimes.Unmarshal(m, b)
}
func (m *CalculatingManyTimes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatingManyTimes.Marshal(b, m, deterministic)
}
func (m *CalculatingManyTimes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatingManyTimes.Merge(m, src)
}
func (m *CalculatingManyTimes) XXX_Size() int {
	return xxx_messageInfo_CalculatingManyTimes.Size(m)
}
func (m *CalculatingManyTimes) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatingManyTimes.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatingManyTimes proto.InternalMessageInfo

func (m *CalculatingManyTimes) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculatorManyTimesRequest struct {
	CalculatingManyTimes *CalculatingManyTimes `protobuf:"bytes,1,opt,name=calculatingManyTimes,proto3" json:"calculatingManyTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CalculatorManyTimesRequest) Reset()         { *m = CalculatorManyTimesRequest{} }
func (m *CalculatorManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorManyTimesRequest) ProtoMessage()    {}
func (*CalculatorManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{4}
}

func (m *CalculatorManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorManyTimesRequest.Unmarshal(m, b)
}
func (m *CalculatorManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorManyTimesRequest.Merge(m, src)
}
func (m *CalculatorManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorManyTimesRequest.Size(m)
}
func (m *CalculatorManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorManyTimesRequest proto.InternalMessageInfo

func (m *CalculatorManyTimesRequest) GetCalculatingManyTimes() *CalculatingManyTimes {
	if m != nil {
		return m.CalculatingManyTimes
	}
	return nil
}

type CalculatorManyTimesResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorManyTimesResponse) Reset()         { *m = CalculatorManyTimesResponse{} }
func (m *CalculatorManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorManyTimesResponse) ProtoMessage()    {}
func (*CalculatorManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c8c7d6609153bff, []int{5}
}

func (m *CalculatorManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorManyTimesResponse.Unmarshal(m, b)
}
func (m *CalculatorManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorManyTimesResponse.Merge(m, src)
}
func (m *CalculatorManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorManyTimesResponse.Size(m)
}
func (m *CalculatorManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorManyTimesResponse proto.InternalMessageInfo

func (m *CalculatorManyTimesResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculating)(nil), "calculator.Calculating")
	proto.RegisterType((*CalculatorRequest)(nil), "calculator.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "calculator.CalculatorResponse")
	proto.RegisterType((*CalculatingManyTimes)(nil), "calculator.CalculatingManyTimes")
	proto.RegisterType((*CalculatorManyTimesRequest)(nil), "calculator.CalculatorManyTimesRequest")
	proto.RegisterType((*CalculatorManyTimesResponse)(nil), "calculator.CalculatorManyTimesResponse")
}

func init() {
	proto.RegisterFile("calculatorService/calculatorpb/calculator.proto", fileDescriptor_5c8c7d6609153bff)
}

var fileDescriptor_5c8c7d6609153bff = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0xa9, 0xe0, 0x1e, 0x5e, 0xab, 0x60, 0x5c, 0x54, 0x2a, 0xca, 0x1a, 0x41, 0x3d, 0x48,
	0x95, 0x15, 0x0f, 0x5e, 0xdd, 0xa3, 0xb8, 0x87, 0xba, 0x5e, 0xbc, 0x48, 0x1b, 0xa3, 0x16, 0xba,
	0x49, 0x4d, 0x52, 0xc1, 0xaf, 0xe8, 0xa7, 0x12, 0xd3, 0x6c, 0xf3, 0x94, 0xac, 0x1e, 0xdf, 0x64,
	0x32, 0xf3, 0xcb, 0x1f, 0x38, 0x63, 0x45, 0xcd, 0xda, 0xba, 0x30, 0x52, 0xdd, 0x71, 0xf5, 0x5e,
	0x31, 0x8e, 0x94, 0xa6, 0x44, 0x43, 0xd6, 0x28, 0x69, 0x24, 0x01, 0xaf, 0xd0, 0x7b, 0x88, 0x27,
	0x6e, 0xaa, 0xc4, 0x0b, 0x39, 0x80, 0xe4, 0xb9, 0x52, 0xda, 0x3c, 0x8a, 0x76, 0x5e, 0x72, 0xb5,
	0x13, 0x8d, 0xa2, 0x93, 0xd5, 0x3c, 0xb6, 0xda, 0xd4, 0x4a, 0xe4, 0x10, 0xd6, 0x34, 0x67, 0x52,
	0x3c, 0x2d, 0x3c, 0x2b, 0xd6, 0x93, 0x74, 0x62, 0x67, 0xa2, 0x53, 0xd8, 0x98, 0xf4, 0x25, 0x39,
	0x7f, 0x6b, 0xb9, 0x36, 0xe4, 0x0a, 0x62, 0xe6, 0xbb, 0x6c, 0x76, 0x3c, 0xde, 0xce, 0x10, 0x1f,
	0x42, 0xc9, 0xb1, 0x97, 0x9e, 0x02, 0xc1, 0x79, 0xba, 0x91, 0x42, 0x73, 0xb2, 0x05, 0x03, 0xc5,
	0x75, 0x5b, 0x1b, 0xc7, 0xe9, 0x26, 0x9a, 0xc1, 0x10, 0x25, 0xdd, 0x16, 0xe2, 0x63, 0x56, 0xcd,
	0xb9, 0xfe, 0xf6, 0xff, 0x38, 0x97, 0x9b, 0xa8, 0x82, 0xd4, 0xa7, 0xf7, 0xf6, 0x05, 0xf6, 0x0c,
	0x86, 0x2c, 0x90, 0xe6, 0xf8, 0x47, 0x4b, 0xf8, 0x7d, 0x4c, 0x70, 0x37, 0xbd, 0x84, 0xdd, 0x60,
	0xe7, 0xdf, 0x47, 0x1b, 0x7f, 0x46, 0xf8, 0x66, 0xdd, 0x7b, 0x93, 0x1b, 0x00, 0x2f, 0x92, 0xbd,
	0x10, 0x52, 0xff, 0x0c, 0xe9, 0xfe, 0xb2, 0x65, 0x57, 0xfd, 0x0a, 0x9b, 0x01, 0x32, 0x72, 0x14,
	0xde, 0xf6, 0xfb, 0xba, 0xd2, 0xe3, 0x7f, 0x7d, 0x5d, 0xcf, 0x79, 0x74, 0xbd, 0xfe, 0x90, 0xe0,
	0x9f, 0x5a, 0x0e, 0xec, 0xff, 0xbc, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xf3, 0x23, 0xee,
	0xd2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	CalculatorManyTimes(ctx context.Context, in *CalculatorManyTimesRequest, opts ...grpc.CallOption) (CalculatorService_CalculatorManyTimesClient, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) CalculatorManyTimes(ctx context.Context, in *CalculatorManyTimesRequest, opts ...grpc.CallOption) (CalculatorService_CalculatorManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/CalculatorManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculatorManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_CalculatorManyTimesClient interface {
	Recv() (*CalculatorManyTimesResponse, error)
	grpc.ClientStream
}

type calculatorServiceCalculatorManyTimesClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculatorManyTimesClient) Recv() (*CalculatorManyTimesResponse, error) {
	m := new(CalculatorManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Calculator(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	CalculatorManyTimes(*CalculatorManyTimesRequest, CalculatorService_CalculatorManyTimesServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Calculator(ctx context.Context, req *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculator not implemented")
}
func (*UnimplementedCalculatorServiceServer) CalculatorManyTimes(req *CalculatorManyTimesRequest, srv CalculatorService_CalculatorManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculatorManyTimes not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Calculator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculator(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_CalculatorManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalculatorManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).CalculatorManyTimes(m, &calculatorServiceCalculatorManyTimesServer{stream})
}

type CalculatorService_CalculatorManyTimesServer interface {
	Send(*CalculatorManyTimesResponse) error
	grpc.ServerStream
}

type calculatorServiceCalculatorManyTimesServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculatorManyTimesServer) Send(m *CalculatorManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculator",
			Handler:    _CalculatorService_Calculator_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CalculatorManyTimes",
			Handler:       _CalculatorService_CalculatorManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculatorService/calculatorpb/calculator.proto",
}
